services:
    mozart.post.post_type_manager:
        class: Mozart\Component\Post\Type\PostTypeManager

    mozart.post.manager:
        class: Mozart\Bundle\PostBundle\Model\PostManager
        arguments:
            - @service_container

    mozart.post.meta.manager:
        class: Mozart\Bundle\PostBundle\Model\PostMetaManager
        arguments:
            - @service_container

    mozart.post.attachment_manager:
        class: Mozart\Bundle\PostBundle\Model\AttachmentManager
        arguments:
            - @service_container
