services:
    mozart_shortcode.shortcode_chain:
        class: Mozart\Bundle\ShortcodeBundle\ShortcodeChain

    mozart_shortcode.shortcode.caption:
        class: Mozart\Bundle\ShortcodeBundle\Shortcode\CaptionShortcode
        tags:
            - { name: wordpress.shortcode }

    mozart_shortcode.shortcode.content_box:
        class: Mozart\Bundle\ShortcodeBundle\Shortcode\ContentBoxShortcode
        tags:
            - { name: wordpress.shortcode }

    mozart_shortcode.shortcode.row:
        class: Mozart\Bundle\ShortcodeBundle\Shortcode\RowShortcode
        tags:
            - { name: wordpress.shortcode }

    mozart_shortcode.shortcode.span3:
        class: Mozart\Bundle\ShortcodeBundle\Shortcode\Columns\Col3Shortcode
        tags:
            - { name: wordpress.shortcode }
    mozart_shortcode.shortcode.span4:
        class: Mozart\Bundle\ShortcodeBundle\Shortcode\Columns\Col4Shortcode
        tags:
            - { name: wordpress.shortcode }
    mozart_shortcode.shortcode.span6:
        class: Mozart\Bundle\ShortcodeBundle\Shortcode\Columns\Col6Shortcode
        tags:
            - { name: wordpress.shortcode }
    mozart_shortcode.shortcode.span8:
        class: Mozart\Bundle\ShortcodeBundle\Shortcode\Columns\Col8Shortcode
        tags:
            - { name: wordpress.shortcode }
    mozart_shortcode.shortcode.span9:
        class: Mozart\Bundle\ShortcodeBundle\Shortcode\Columns\Col9Shortcode
        tags:
            - { name: wordpress.shortcode }
