services:
    mozart.user.meta.manager:
        class: Mozart\Bundle\UserBundle\Model\UserMetaManager
        arguments:
            - @service_container
    mozart.user.widget.login:
        class: Mozart\Bundle\UserBundle\Widget\LoginWidget
        arguments:
            - @templating
        tags:
            - { name: wordpress.widget }
    mozart.user.widget.register:
        class: Mozart\Bundle\UserBundle\Widget\RegisterWidget
        arguments:
            - @templating
        tags:
            - { name: wordpress.widget }
