parameters:
    mozart_nucleus.configuration.manager.class: Mozart\Bundle\NucleusBundle\Wordpress\ConfigurationManager
    mozart_nucleus.security.authentication.provider.class: Mozart\Bundle\NucleusBundle\Security\Authentication\Provider\WordpressProvider
    mozart_nucleus.security.authentication.listener.class: Mozart\Bundle\NucleusBundle\Security\Firewall\WordpressListener
    mozart_nucleus.security.logout.handler.cookie_clearing.class: Mozart\Bundle\NucleusBundle\Security\Http\Logout\WordpressCookieClearingLogoutHandler
    mozart_nucleus.security.cookie.service.class: Mozart\Bundle\NucleusBundle\Security\Http\WordpressCookieService
    mozart_nucleus.security.encoder.phpass.class: Mozart\Bundle\NucleusBundle\Security\Encoder\PhpassPasswordEncoder
    mozart_nucleus.table_prefix.subscriber.class: Mozart\Bundle\NucleusBundle\Subscriber\TablePrefixSubscriber

services:
    mozart_nucleus.twig.extension:
        class: Mozart\Bundle\NucleusBundle\Twig\Extension\NucleusExtension
        arguments:
            - @service_container
        tags:
            - {name: twig.extension}

    mozart_nucleus.twig.wordpress:
        class: Mozart\Bundle\NucleusBundle\Twig\Extension\WordpressExtension
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }
            
    mozart_nucleus.configuration.manager:
        class: %mozart_nucleus.configuration.manager.class%
        arguments:
            - %wp.site.uri%
            - %wp.cookie.path%
            - %wp.cookie.domain%
            - %wp.key.logged_in%
            - %wp.salt.logged_in%

    mozart_nucleus.security.authentication.provider:
        class: %mozart_nucleus.security.authentication.provider.class%
        public: false

    mozart_nucleus.security.authentication.listener:
        class: %mozart_nucleus.security.authentication.listener.class%
        arguments:
            - @security.context
            - @mozart_nucleus.security.cookie.service
            - @security.authentication.manager
            - @logger
            - @event_dispatcher
        tags:
            - {name: monolog.logger, channel: security}

    mozart_nucleus.security.logout.handler.cookie_clearing:
        class: %mozart_nucleus.security.logout.handler.cookie_clearing.class%
        parent: security.logout.handler.cookie_clearing
        arguments:
            - @mozart_nucleus.configuration.manager

    mozart_nucleus.security.cookie.service:
        class: %mozart_nucleus.security.cookie.service.class%

    mozart_nucleus.security.encoder.phpass:
        class: %mozart_nucleus.security.encoder.phpass.class%

    mozart_nucleus.table_prefix.subscriber:
        class: %mozart_nucleus.table_prefix.subscriber.class%
        arguments:
            - %database_table_prefix%
        tags:
            - {name: doctrine.event_subscriber}