parameters:
    mozart.configuration.manager.class: Mozart\Bundle\NucleusBundle\Wordpress\ConfigurationManager
    mozart.security.authentication.provider.class: Mozart\Bundle\NucleusBundle\Security\Authentication\Provider\WordpressProvider
    mozart.security.authentication.listener.class: Mozart\Bundle\NucleusBundle\Security\Firewall\WordpressListener
    mozart.security.logout.handler.cookie_clearing.class: Mozart\Bundle\NucleusBundle\Security\Http\Logout\WordpressCookieClearingLogoutHandler
    mozart.security.cookie.service.class: Mozart\Bundle\NucleusBundle\Security\Http\WordpressCookieService
    mozart.security.encoder.phpass.class: Mozart\Bundle\NucleusBundle\Security\Encoder\PhpassPasswordEncoder
    mozart.table_prefix.subscriber.class: Mozart\Bundle\NucleusBundle\Subscriber\TablePrefixSubscriber

services:
    mozart.multisite:
        class: Mozart\Component\Multisite\Multisite

    mozart.twig.extension:
        class: Mozart\Bundle\NucleusBundle\Twig\Extension\NucleusExtension
        arguments:
            - @service_container
        tags:
            - {name: twig.extension}

    mozart.twig.wordpress:
        class: Mozart\Bundle\NucleusBundle\Twig\Extension\WordpressExtension
        arguments:
            - @mozart.blog.manager
            - @mozart.config.manager
            - @mozart.post.manager
            - @mozart.post.meta.manager
            - @mozart.post.attachment_manager
            - @mozart.taxonomy.term.manager
            - @mozart.user.meta.manager
            - @mozart.comment.manager
        tags:
            - { name: twig.extension }

    mozart.configuration.manager:
        class: %mozart.configuration.manager.class%
        arguments:
            - %wp.site.uri%
            - %wp.cookie.path%
            - %wp.cookie.domain%
            - %wp.key.logged_in%
            - %wp.salt.logged_in%

    mozart.security.authentication.provider:
        class: %mozart.security.authentication.provider.class%
        public: false

    mozart.security.authentication.listener:
        class: %mozart.security.authentication.listener.class%
        arguments:
            - @security.context
            - @mozart.security.cookie.service
            - @security.authentication.manager
            - @logger
            - @event_dispatcher
        tags:
            - {name: monolog.logger, channel: security}

    mozart.security.logout.handler.cookie_clearing:
        class: %mozart.security.logout.handler.cookie_clearing.class%
        parent: security.logout.handler.cookie_clearing
        arguments:
            - @mozart.configuration.manager

    mozart.security.cookie.service:
        class: %mozart.security.cookie.service.class%

    mozart.security.encoder.phpass:
        class: %mozart.security.encoder.phpass.class%

    mozart.table_prefix.subscriber:
        class: %mozart.table_prefix.subscriber.class%
        arguments:
            - %database_table_prefix%
        tags:
            - {name: doctrine.event_subscriber}

    mozart.nucleus.option.section:
        class: Mozart\Bundle\NucleusBundle\Option\Section\MozartSection
        tags:
            - {name: mozart.config.section, alias: mozart}
