services:
    config.storage:
        class: Mozart\Component\Config\Storage\DatabaseStorage

    config.factory:
        class: Mozart\Component\Config\ConfigFactory
        arguments:
            - @config.storage

    config.manager:
        class: Mozart\Bundle\ConfigBundle\Model\OptionManager
        arguments:
            - @service_container

    mozart.config.twig.extension:
        class: Mozart\Bundle\ConfigBundle\Twig\Extension\OptionTemplateExtension
        arguments:
            - @config.factory
            - @config.manager
            - []
        tags:
            - { name: twig.extension }

    mozart.config.page.manager:
        class: Mozart\Component\Config\Page\BaseConfigPageManager

    mozart.config.page.fieldgroup.manager:
        class: Mozart\Component\Config\Page\BaseFieldGroupManager