services:
    mozart.option.importer:
        class: Mozart\Component\Option\Importer
    mozart.option.debugger:
        class: Mozart\Component\Option\Debugger
    mozart.option.tracker:
        class: Mozart\Component\Option\Tracker
    mozart.option.builder:
        class: Mozart\Component\Option\OptionBuilder
        arguments:
            - @mozart.option.importer
            - @mozart.option.debugger
            - @mozart.option.tracker
            - @mozart.option.extensionmanager
            - @mozart.option.sectionmanager
    mozart.option.manager:
        class: Mozart\Bundle\OptionBundle\Model\OptionManager
        arguments:
            - @service_container
    mozart.option.sectionmanager:
        class: Mozart\Component\Option\Section\SectionManager
    mozart.option.extensionmanager:
        class: Mozart\Component\Option\Extension\ExtensionManager
    mozart.option.controller:
        class: Mozart\Bundle\OptionBundle\Controller\OptionController
        arguments:
            - @mozart.option.builder
            - %mozart.option%
    mozart.option.extension.core.customizer:
        class: Mozart\Component\Option\Extension\Core\CustomizerExtension
        tags:
            - { name: mozart.option.extension }
        arguments:
            - @request_stack
