services:
    mozart.option.builder:
        class: Mozart\Bundle\OptionBundle\Builder\OptionBuilder
    mozart.option.manager:
        class: Mozart\Bundle\OptionBundle\Model\OptionManager
        arguments:
            - @service_container
    mozart.option.sectionmanager:
        class: Mozart\Bundle\OptionBundle\SectionManager
    mozart.option.extensionmanager:
        class: Mozart\Bundle\OptionBundle\Extension\ExtensionManager
    mozart.option.controller:
        class: Mozart\Bundle\OptionBundle\Controller\OptionController
        arguments:
            - @mozart.option.builder
            - @mozart.option.sectionmanager
            - @mozart.option.extensionmanager
    mozart.option.extension.core.customizer:
        class: Mozart\Bundle\OptionBundle\Extension\Core\CustomizerExtension
        tags:
            - { name: mozart.option.extension }
        arguments:
            - @mozart.option.builder
            - @request_stack
