services:
    mozart_taxonomy.taxonomy_manager:
        class: Mozart\Bundle\TaxonomyBundle\TaxonomyManager

    mozart_taxonomy.term.manager:
        class: Mozart\Bundle\TaxonomyBundle\Model\TermManager
        arguments:
            - @service_container
