services:
    mozart_taxonomy.taxonomy_chain:
        class: Mozart\Bundle\TaxonomyBundle\TaxonomyChain

    mozart_taxonomy.taxonomy.caption:
        class: Mozart\Bundle\TaxonomyBundle\Shortcode\CaptionShortcode
        tags:
            - { name: wordpress.taxonomy }
