services:
    mozart.taxonomy.taxonomy_manager:
        class: Mozart\Bundle\TaxonomyBundle\TaxonomyManager

    mozart.taxonomy.term.manager:
        class: Mozart\Bundle\TaxonomyBundle\Model\TermManager
        arguments:
            - @service_container
