services:
    mozart_post.manager:
        class: Mozart\Bundle\PostBundle\Model\PostManager
        arguments:
            - @service_container

    mozart_post.meta.manager:
        class: Mozart\Bundle\PostBundle\Model\PostMetaManager
        arguments:
            - @service_container